// app/api/admin/export/route.js
import { NextResponse } from 'next/server';
import { authenticateAdmin, getDonations } from '@/lib/queries';

export async function GET(request) {
  // Verify admin credentials
  const username = request.headers.get('x-admin-user');
  const password = request.headers.get('x-admin-pass');

  // Also support legacy single-password header (redirects to DB auth)
  const legacyPass = request.headers.get('x-admin-password');

  let authorized = false;
  let adminUser = null;

  if (username && password) {
    adminUser = await authenticateAdmin(username, password);
    if (adminUser) authorized = true;
  }

  if (!authorized) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { searchParams } = new URL(request.url);
  const format = searchParams.get('format') || 'csv';
  const emailTo = searchParams.get('email');

  try {
    const donations = await getDonations();

    // Build CSV
    const headers = ['ID', 'Donor Name', 'Email', 'Amount (৳)', 'Category', 'Type', 'Payment', 'Campaign ID', 'Message', 'Anonymous', 'Status', 'Approved By', 'Approved At', 'Date'];

    const rows = donations.map(d => [
      d.id,
      d.donorName || '',
      d.email || '',
      d.amount || 0,
      d.category || '',
      d.donationType || '',
      d.paymentMethod || '',
      d.campaignId || '',
      (d.message || '').replace(/,/g, ';').replace(/\n/g, ' '),
      d.anonymous ? 'Yes' : 'No',
      d.status || '',
      d.approvedBy || '',
      d.approvedAt || '',
      d.createdAt?.seconds
        ? new Date(d.createdAt.seconds * 1000).toISOString()
        : '',
    ]);

    const csvContent = [headers, ...rows]
      .map(row => row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(','))
      .join('\n');

    // If email requested, try to send
    if (emailTo) {
      try {
        const nodemailer = require('nodemailer');
        const transporter = nodemailer.createTransport({
          host: process.env.SMTP_HOST || 'smtp.gmail.com',
          port: Number(process.env.SMTP_PORT) || 587,
          secure: false,
          auth: {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASS,
          },
        });

        const filename = `alnoor-donations-${new Date().toISOString().slice(0, 10)}.csv`;

        await transporter.sendMail({
          from: process.env.SMTP_USER || 'noreply@alnoormasjid.org',
          to: emailTo,
          subject: `Al-Noor Masjid — Donation Report (${new Date().toLocaleDateString()})`,
          text: `Attached is the complete donation report with ${donations.length} records.\n\nGenerated by: ${adminUser?.username || 'Admin'}\nDate: ${new Date().toLocaleString()}`,
          attachments: [
            {
              filename,
              content: Buffer.from('\uFEFF' + csvContent, 'utf-8'), // BOM for Excel
              contentType: 'text/csv',
            },
          ],
        });

        return NextResponse.json({
          success: true,
          message: `Report sent to ${emailTo}`,
          records: donations.length,
        });
      } catch (emailError) {
        console.error('Email error:', emailError);
        return NextResponse.json({
          error: 'Email failed — check SMTP settings in .env.local',
          details: emailError.message,
        }, { status: 500 });
      }
    }

    // Default: return CSV as downloadable file
    const filename = `alnoor-donations-${new Date().toISOString().slice(0, 10)}.csv`;

    return new NextResponse('\uFEFF' + csvContent, {
      status: 200,
      headers: {
        'Content-Type': 'text/csv; charset=utf-8',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Cache-Control': 'no-store',
      },
    });

  } catch (error) {
    console.error('Export error:', error);
    return NextResponse.json({ error: 'Export failed.' }, { status: 500 });
  }
}
